name: Continuous Integration

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use GitHub Secret
        run: echo "The secret value is $MY_SECRET"
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
